export {
    func "get_stack" return:true {
        catch {
            throw (new MathError "oh no");
        } [MathError "e"] {
            # we don't care about the last 2 frames
            # one is calling catch, the other is this catching block
            return (e.stack.value.slice 0 (e.stack.value.length - 2));
        };

        # the return in the catch should always run
        assert false;
    };

    var StackFrame = (get_class ((get_stack).get 0));
};
